### ISSUE TITLE
popweb-latex always show the `\label` of latex environments

### ISSUE THREAD

**Issue by nujabse** [manateelazycat/popweb#21]
The `popweb` package is amazing! However, I have found a tiny problem when started using this package daily. When rendering latex equations using `popweb`, it sometimes can be very annoying to have the `\label` of the equations rendered together with the equation.
For example, the following latex equation would be rendered like this:
```latex
   \begin{equation}
     \label{eq:11}
     E = mc^{2}
   \end{equation}
```
![image](https://user-images.githubusercontent.com/9455367/143795462-9bce1181-ab41-4ccc-a1af-2b2ed9aa8159.png)
It would be nice if we could have an option to toggle the display of `\label` in rendered latex popup.

**Comment by MatthewZMD** [comment]
This has been fixed in the latest patch
