### ISSUE TITLE
Mac M1 popweb-latex do not display with Emacs fullscreen

### ISSUE THREAD

**Issue by Jousimies** [manateelazycat/popweb#29]
When I use Emacs with `toggle-frame-fullscreen`, the latex preview can not display in front of emacs. It displayed
 in another workspace.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/72933939/167380944-5fdbc958-a3ab-4696-af39-7840e6a6a63e.png">
Can not see the preview

<img width="280" alt="image" src="https://user-images.githubusercontent.com/72933939/167380971-722f1f1e-e162-49f1-a3fe-c3cd5f7704ab.png">
Can be seen in another workspace

If I use Emacs with `toggle-frame-maximized`, the latex preview do work.
<img width="429" alt="image" src="https://user-images.githubusercontent.com/72933939/167381247-7bd753ea-04ad-4045-9130-18ef3560a3b3.png">

the *popweb* buffer:

```
qt.webenginecontext: 

GL Type: core_profile
Surface Type: OpenGL
Surface Profile: CoreProfile
Surface Version: 4.1
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes
Init Parameters:
  *  application-name Python 
  *  browser-subprocess-path /Users/duanning/Library/Python/3.8/lib/python/site-packages/PyQt6/Qt6/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess 
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl core_profile 

js: Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
js: Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
js: Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')

```

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/lazycat-emacs/blob/d90278a2a9d5695b5264d8274d977bc1c46d5ea8/site-lisp/config/init-fullscreen.el#L93
