### ISSUE TITLE
youdao翻译，窗口宽度无法显示完整行信息

### ISSUE THREAD

**Issue by donaldsdlo** [manateelazycat/popweb#36]
windows 11
emacs 28.1
显示的状态如下：
![image](https://user-images.githubusercontent.com/17741154/202842703-380daae2-fd5b-48f4-af65-aec5c2404d0c.png)

**Comment by manateelazycat** [comment]
![截图 2022-11-19 18-09-44](https://user-images.githubusercontent.com/237487/202845717-35205d5e-8781-4b24-b5ea-717a096f1df7.png)

我没有你右上角的图， 也没有显示不全的问题。

**Comment by manateelazycat** [comment]
没法重现，抱歉。
