### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Jousimies** [manateelazycat/popweb#4]
`M-x popweb-katex-show` , the latex preview is well. But if I continue press right arrow key make cursor move from beginning to the end of the formula, the `*popweb*` buffer will throw error about `TypeError: unsupported operand type(s) for *: 'NoneType' and 'int' `.

```
js: Uncaught TypeError: Cannot read property 'offsetWidth' of null
js: Uncaught TypeError: Cannot read property 'offsetHeight' of null
Traceback (most recent call last):
  File "/home/dn/.emacs.d/site-lisp/packages/popweb/popweb.py", line 356, in render_katex
    self.web_window.resize(int(render_width * self.web_window.zoom_factor * 1.2),
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
The org file
```
$\frac{1}{2}$

$\sigma_{1}^{2} / f$
```
If I re-exectute the `popweb-katex-show` command, the preview will work well again.

The error only occur when continue press key, If press and free the key, the preview works well.

**Comment by manateelazycat** [comment]
has fixed
