### ISSUE TITLE
Lisp error: (void-variable gnus-button-url-regexp)

### ISSUE THREAD

**Issue by bbenchen** [manateelazycat/popweb#41]
Debugger entered--Lisp error: (void-variable gnus-button-url-regexp)
  popweb-current-line-url()
  popweb-url-prompt-input("preview url: ")
  popweb-url-input()
  #<subr funcall-interactively>(popweb-url-input)
  apply(#<subr funcall-interactively> popweb-url-input)
  funcall-interactively(popweb-url-input)
  #<subr call-interactively>(popweb-url-input record nil)
  apply(#<subr call-interactively> (popweb-url-input record nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> popweb-url-input record nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (popweb-url-input record nil))
  call-interactively(popweb-url-input record nil)
  command-execute(popweb-url-input record)
  execute-extended-command(nil "popweb-url-input" nil)
  #<subr funcall-interactively>(execute-extended-command nil "popweb-url-input" nil)
  apply(#<subr funcall-interactively> (execute-extended-command nil "popweb-url-input" nil))
  funcall-interactively(execute-extended-command nil "popweb-url-input" nil)
  #<subr call-interactively>(execute-extended-command nil nil)
  apply(#<subr call-interactively> (execute-extended-command nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> execute-extended-command nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (execute-extended-command nil nil))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by bbenchen** [comment]
环境是emacs 28.2

**Comment by ginqi7** [comment]
gnus-button-url-regexp 应该是27.1 就引入了的默认变量。不知道为何你这边没有。
![image](https://user-images.githubusercontent.com/1028971/205825369-c7298dcf-f1a5-4bb8-a71b-d9512186c259.png)
可以考虑，先手动定义一下，我后续看看是否替换掉这个变量。

``` emacs-lisp
(setq  gnus-button-url-regexp "\\b\\(\\(www\\.\\|\\(s?https?\\|ftp\\|file\\|gopher\\|gemini\\|nntp\\|news\\|telnet\\|wais\\|mailto\\|info\\):\\)\\(//[-a-z0-9_.]+:[0-9]*\\)?\\(?:[-a-z0-9_=#$@~%&*+\\/[:word:]!?:;.,]+([-a-z0-9_=#$@~%&*+\\/[:word:]!?:;.,]+)\\(?:[-a-z0-9_=#$@~%&*+\\/[:word:]!?:;.,]+[-a-z0-9_=#$@~%&*+\\/[:word:]]\\)?\\|[-a-z0-9_=#$@~%&*+\\/[:word:]!?:;.,]+[-a-z0-9_=#$@~%&*+\\/[:word:]]\\)\\)")
```

**Comment by manateelazycat** [comment]
那是因为需要用户手动 import gnus-art @ginqi7 

已经修复了。
