### ISSUE TITLE
在MACOS中将pyQT6更新到6.4.0后，翻译页面显示内容为空并且窗口还有一些错位

### ISSUE THREAD

**Issue by bbenchen** [manateelazycat/popweb#46]
由于更新了EAF，并且EAF将pyQT6更新6.4.0后，再次使用翻译功能无法正常显示

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/2104470/209583059-e52ea2c7-2d13-4f7b-8e7f-e9b72302c1ed.png">

**Comment by bbenchen** [comment]
将pyQT6降级到6.3.1，就可以正常显示

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/2104470/209583804-e6c40bed-0805-49c1-b3d1-42b3b31c9e05.png">

**Comment by manateelazycat** [comment]
应该是 PyQt 6.4 默认的安全设置导致脚本运行有问题。

**Comment by manateelazycat** [comment]
https://github.com/emacs-eaf/emacs-application-framework/commit/8410cca2de534d9c2f76ef4d0a672b631318b86a

我推送了 EAF 降级补丁， 暂时可用了， 以后再看看是哪个安全选项导致 popweb 不可用的。
