### ISSUE TITLE
how to scale font-size in popweb?

### ISSUE THREAD

**Issue by nigo81** [manateelazycat/popweb#49]
The font size of popweb-dict-youdao-pointer is too small. Is it possible to scale?
![image](https://user-images.githubusercontent.com/38601513/212468595-fbc37bbe-d5e9-4c33-9fbf-c13c5d7c243c.png)

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/popweb/blob/bd7818e7dbe42dbe185cd55633a840ce446ad277/popweb.py#L199

由 self.zoom_factor 来控制缩放比例的。

你可以通过下面方式来提交补丁：
1. popweb.el 新建两个选项， 一个控制正常缩放比例， 一个控制 4k 缩放比例
2. https://github.com/manateelazycat/popweb/blob/bd7818e7dbe42dbe185cd55633a840ce446ad277/popweb.py#L199 用 get_emacs_vars 来获取 el 选项

**Comment by nigo81** [comment]
感谢懒猫，这个插件和eaf-pdfview对阅读英文文档帮助非常大。

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/popweb/commit/7bd91f8c8180c3d109a1c087a9de1eb3a62a8fba 添加了 popweb-zoom-factor 选项， 直接改这个选项的值就好了。
