### ISSUE TITLE
popweb预览org-roam相关功能报错

### ISSUE THREAD

**Issue by nigo81** [manateelazycat/popweb#50]
在org-roam中执行`popweb-org-roam-link-show`以及其他几个org-roam相关功能会报以下错误：
```
symbol's funtion definition is void:org-blackfriday--reset-org-blackfriday--code-block-num-backticks
```
请问应该怎么解决？

**Comment by manateelazycat** [comment]
google 一下 org-blackfriday--reset-org-blackfriday--code-block-num-backticks， 就知道你缺少啥包了。
